!======================================================================================================================!
!
!                    DassFlow1D Version 2.1
!
!======================================================================================================================!
!
!  Copyright University of Toulouse-INSA - CNRS (France)
!
!  This file is part of the DassFlow software (Data Assimilation for Free Surface Flows).
!  DassFlow is a computational software aiming at simulating geophysical free surface flows.
!  It is designed for Variational Data Assimilation (4D-var) and sensitivity analyses. 
! Inverse capabilities are based on the adjoint code which is generated by 
! a source-to-source algorithmic differentiation (Tapenade software used).
!
!  DassFlow software includes few mostly independent "modules" with common architectures and structures:
!    - DassFlow 2DShallow (shallow water equations in (h,q), finite volumes), i.e. the present code.
!    - DassFlow3D  (non-linear Stokes equations, finite elements, mobile geometries, ALE).
!    - DassFlow 1D (shallow water equations in (S,Q), finite volumes or finite differences), river hydraulics.
!  Please consult the DassFlow webpage for more details: http://www.math.univ-toulouse.fr/DassFlow
!
! You have used DassFlow in an article, a scientific document etc ?  How to cite us ? Please consult the webpage.
! 
!  Many people have contributed to the DassFlow developments from the initial version to the latest ones.
!  Current main developers or scientific contributers are:
!               P. Brisset (CNES & Mathematics Institute of Toulouse & INSA Toulouse)
!               F. Couderc (CNRS & Mathematics Institute of Toulouse IMT)
!               P.-A. Garambois (INSA & ICUBE Strasbourg)
!               J. Monnier (INSA & Mathematics Institute of Toulouse IMT).
!               J.-P. Vila (INSA & Mathematics Institute of Toulouse IMT).
!  and former other developers (R. Madec, M. Honnorat and J. Marin).
!
!  Scientific contact : jerome.monnier@insa-toulouse.fr
!  Technical  contacts : frederic.couderc@math.univ-toulouse.fr, pierre.brisset@insa-toulouse.fr
!
!  This software is governed by the CeCILL license under French law and abiding by the rules of distribution
!  of free software. You can use, modify and/or redistribute the software under the terms of the CeCILL license
!  as circulated by CEA, CNRS and INRIA at the following URL: "http://www.cecill.info".
!
!  As a counterpart to the access to the source code and rights to copy, modify and redistribute granted by the
!  license, users are provided only with a limited warranty and the software's author, the holder of the economic
!  rights, and the successive licensors have only limited liability.
!
!  In this respect, the user's attention is drawn to the risks associated with loading, using, modifying and/or
!  developing or reproducing the software by the user in light of its specific status of free software, that may
!  mean that it is complicated to manipulate, and that also therefore means that it is reserved for developers and
!  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the
!  software's suitability as regards their requirements in conditions enabling the security of their systems and/or
!  data to be ensured and, more generally, to use and operate it in the same conditions as regards security.
!
!  The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you
!  accept its terms.
!
!======================================================================================================================!
!> \file boundary.f90
!! \brief This file includes the computation/update of boundaries conditions and gost cell.

!**********************************************************************************************************************!
!**********************************************************************************************************************!
!
!  Fill Ghost Cells with appropriate values depending of the type of the boundary considered
!
!**********************************************************************************************************************!
!**********************************************************************************************************************!

!>  Fill ghost cells with appropriate values depending of the type of the boundary considered.
!!
!! \details This subroutine compute the boundaries conditions from users informations from input.txt. Gost cell are 
!! filled too.
!! \param[in]    msh Mesh of the problem.
!! \param[in]    dof Unknowns of the model.
SUBROUTINE calc_boundary_state( msh,dof)

   USE m_model
   USE m_numeric
   USE m_user_data

   implicit none

!======================================================================================================================!
!  Interface Variables
!======================================================================================================================!

   type(Mesh), intent(in   )  ::  msh

   type( unk ), intent(inout)  ::  dof
   

!    real(rp) :: HtoS
   real(rp) :: geo_cs_htoA
   integer(ip) :: iflag
   real(rp) :: b, c
   real(rp) :: s,q,h,yav,qav,sav
   real(rp) :: gap_E
   real(rp) :: qn,hfind
   real(rp) :: GetWFromH
   real(rp) :: dhx
   real(rp) :: hbord, hint, ubord, uint
!======================================================================================================================!
!  Begin Subroutine
!======================================================================================================================!


   select case( BC_W )

   !===================================================================================================================!
   !  Inflow Boundary  :  'discharg'
   !===================================================================================================================!

      case('discharg')

         if (bc%typehyd=='file_FS') then
            dof%q(1)=Fourier_Serie( tc,bc%hyd_FS%a0,bc%hyd_FS%n, bc%hyd_FS%A, bc%hyd_FS%B) !( bc%hyd%t ,bc%hyd%q ,tc)
            dof%q(2)=dof%q(1)

            
         else if (bc%typehyd=='file') then
!             dhx=(bathy_cell(2)-bathy_cell(1))/msh%cs(2)%deltademi
            dof%q(1)=linear_interp( bc%hyd%t ,bc%hyd%q ,tc)
            dof%q(2)=linear_interp( bc%hyd%t ,bc%hyd%q ,tc) 
            
         else 
            dof%q(1)=inflow_user(msh%cs(1)%coord%x,msh%cs(1)%coord%y,tc)
            dof%q(2)=inflow_user(msh%cs(1)%coord%x,msh%cs(1)%coord%y,tc)

         endif
            b=dof%h(3)-0.2
            c=dof%h(3)+0.2

            !iflag=0_ip
            !call fzero( findzero,b,c,0.000001_rp,0.000001_rp,iflag ) !NOADJ
            iflag=1
            if (iflag.eq.1) then
               if (((b+c)*0.5_rp).le.0) then
                  dof%s(1)=dof%s(3)
                  dof%s(2)=dof%s(3)
                  dof%h(1)=dof%h(3)
                  dof%h(2)=dof%h(3)
               endif
               hfind=(b+c)*0.5_rp
             
               dof%s(1) = geo_cs_htoA(msh%cs(2), hfind)
               dof%s(2)=dof%s(1)
               dof%h(1)=max(heps, hfind)
               dof%h(2)=max(heps, hfind)
     
            else
               dof%s(1)=dof%s(3)
               dof%s(2)=dof%s(3)
               dof%h(1)=dof%h(3)
               dof%h(2)=dof%h(3)
            endif



         !surfaceWidth(1)=GetWFromH(msh,dof%h(3),1)
         !surfaceWidth(2)=GetWFromH(msh,dof%h(3),2)
         !dof%w(1)=GetWFromH(msh,dof%h(3),1)         
         !dof%w(2)=dof%w(1)

      case('discharg1')

         if (bc%typehyd=='file_FS') then
            dof%q(1)=Fourier_Serie( tc,bc%hyd_FS%a0,bc%hyd_FS%n, bc%hyd_FS%A, bc%hyd_FS%B) !( bc%hyd%t ,bc%hyd%q ,tc)
            dof%q(2)=dof%q(1)

            
         else if (bc%typehyd=='file') then
!             dhx=(bathy_cell(2)-bathy_cell(1))/msh%cs(2)%deltademi
            dof%q(1)=linear_interp( bc%hyd%t ,bc%hyd%q ,tc)
            dof%q(2)=linear_interp( bc%hyd%t ,bc%hyd%q ,tc) 
            
         else 
            dof%q(1)=inflow_user(msh%cs(1)%coord%x,msh%cs(1)%coord%y,tc)
            dof%q(2)=inflow_user(msh%cs(1)%coord%x,msh%cs(1)%coord%y,tc)

         endif
         
         ubord = dof%q(2) / dof%s(2)
         uint = dof%q(3) / dof%s(3)
         hint = dof%h(3)
         hbord = (ubord - uint + sqrt(g * hint))**2 / g
         dof%s(2) = geo_cs_htoA(msh%cs(2), hbord)
         dof%s(1) = dof%s(2)
         dof%h(2) = hbord
         dof%h(1) = hbord

      case ('neumann')
         dof%q(1)=dof%q(3)
         dof%q(2)=dof%q(3)

         dof%s(1)=dof%s(3)
         dof%s(2)=dof%s(3)

      case ('wall')
         dof%q(1)=-dof%q(3)
         dof%q(2)=-dof%q(3)

         dof%s(1)=dof%s(3)
         dof%s(2)=dof%s(3)


      case default
         write (*,'(A20)') 'W boundary condition no-defined' !NOADJ
         dof%q(1)=-dof%q(3)
         dof%q(2)=-dof%q(3)

         dof%s(1)=dof%s(3)
         dof%s(2)=dof%s(3)


   end select

   select case( BC_E )

   !===================================================================================================================!
   !  Outflow Boundary  :  'ratcurve'
   !===================================================================================================================!

      case('ratcurve')
         
         if (bc%typerat=='file') then  
            !gap_E=bathy_cell(msh%ncs+2)-bathy_cell(msh%ncs+2-addPointsE)
            dof%h(msh%ncs+3)=linear_interp( bc%rat%q ,&
                                             bc%rat%h ,&
                                             abs(dof%q(msh%ncs+2)))&
                              !-gap_E &
                              -bathy_cell(msh%ncs+2)

            dof%h(msh%ncs+4)=linear_interp( bc%rat%q ,&
                                             bc%rat%h ,&
                                             abs(dof%q(msh%ncs+2)))&
                              !-gap_E &
                              -bathy_cell(msh%ncs+2)

            

            dof%s(msh%ncs+3) = geo_cs_htoA(msh%cs(msh%ncs+3), dof%h(msh%ncs+3))
            dof%s(msh%ncs+4) = geo_cs_htoA(msh%cs(msh%ncs+4), dof%h(msh%ncs+4))


         !elseif ((alpha_ratcurve.ne.0._rp).or.(beta_ratcurve.ne.0._rp)) then
         elseif (c_ratcurve.eq.2) then  
         
            dof%h(msh%ncs+3)=alpha_ratcurve*(abs(dof%q(msh%ncs+2)))**beta_ratcurve                                

            dof%h(msh%ncs+4)=alpha_ratcurve*(abs(dof%q(msh%ncs+2)))**beta_ratcurve                                       


            dof%s(msh%ncs+4) = geo_cs_htoA(msh%cs(msh%ncs+4), abs(dof%h(msh%ncs+4)))

            dof%s(msh%ncs+3) = geo_cs_htoA(msh%cs(msh%ncs+3), abs(dof%h(msh%ncs+3)))

            
         else 
         
            dof%s(msh%ncs+4)=outflow_user(msh%cs(msh%ncs)%coord%x,msh%cs(msh%ncs)%coord%y,tc)
            dof%s(msh%ncs+3)=outflow_user(msh%cs(msh%ncs)%coord%x,msh%cs(msh%ncs)%coord%y,tc)

         endif
            !if (iflag.eq.1) then
            !   dof%s(msh%ncs+4)=4*qav-3*qn
            !   dof%s(msh%ncs+3)=2*qav-  qn                             

            !else 


          !dof%q(msh%ncs+2)=65.0_rp
          dof%q(msh%ncs+4)=dof%q(msh%ncs+2)
          dof%q(msh%ncs+3)=dof%q(msh%ncs+2)
            !end if

         !surfaceWidth(msh%ncs+3)=GetWFromH(msh,dof%h(msh%ncs+3),msh%ncs+3)
         !surfaceWidth(msh%ncs+4)=GetWFromH(msh,dof%h(msh%ncs+4),msh%ncs+4)
         !dof%w(msh%ncs+3)=GetWFromH(msh,dof%h(msh%ncs+3),msh%ncs+3)         
         !dof%w(msh%ncs+4)=GetWFromH(msh,dof%h(msh%ncs+4),msh%ncs+4)


      case ('neumann')
         dof%q(msh%ncs+4)=dof%q(msh%ncs+2)
         dof%q(msh%ncs+3)=dof%q(msh%ncs+2)

         dof%s(msh%ncs+4)=dof%s(msh%ncs+2)
         dof%s(msh%ncs+3)=dof%s(msh%ncs+2)
         dof%h(msh%ncs+4)=dof%h(msh%ncs+2)
         dof%h(msh%ncs+3)=dof%h(msh%ncs+2)


      case ('normal_depth')
      
         ! TODO

      case ('elevation')
      
         dof%h(msh%ncs+2) = linear_interp( bc%dsz%t ,bc%dsz%y ,tc) - bathy_cell(msh%ncs+2)
         dof%h(msh%ncs+3) = dof%h(msh%ncs+2)
         dof%h(msh%ncs+4) = dof%h(msh%ncs+2)

      case ('wall')
         
         dof%q(msh%ncs+4)=-dof%q(msh%ncs+2)
         dof%q(msh%ncs+3)=-dof%q(msh%ncs+2)

         dof%s(msh%ncs+4)=dof%s(msh%ncs+2)
         dof%s(msh%ncs+3)=dof%s(msh%ncs+2)


      case default
         write (*,'(A20)') 'W boundary condition no-defined', BC_W !NOADJ

   end select



contains

   real(rp) function findzero(x)
      implicit none
      real(rp)  :: x 
      real(rp) :: s,h,q,qam
      
      s=dof%s(3)
      h=dof%h(3)
      q=dof%q(3)
      qam=dof%q(1)
      findzero=qam*(h/s) +x*(-2._rp*sqrt(g*x)-q/s +2._rp*sqrt(g*h))
      return
   end function findzero

END SUBROUTINE calc_boundary_state




   SUBROUTINE compute_qlat(dof)
   
   use m_numeric
   use m_sw_mono
   
   implicit none
   
   !===================================================================================================================!
   ! Global variables
   !===================================================================================================================!

   type( unk ), intent(inout)  ::  dof

   !===================================================================================================================!
   ! Local variables
   !===================================================================================================================!
   
   integer :: times, space, loc

       
       space = size(bc%hyd_lat%x)
       times = size(bc%hyd_lat%t)
       !!!Interpolate Q for i at tc

     do i = 1,space
     
        dof%qlat(2,i)=linear_interp( bc%hyd_lat%t ,bc%hyd_lat%q(i,1:times) ,tc+dt) !Interpolate lateral inflow at current time

     end do
     
     
    END SUBROUTINE compute_qlat

