!======================================================================================================================!
!
!                    DassFlow Version 2.0
!
!======================================================================================================================!
!
!  Copyright University of Toulouse-INSA - CNRS (France)
!
!  This file is part of the DassFlow software (Data Assimilation for Free Surface Flows).
!  DassFlow is a computational software aiming at simulating geophysical free surface flows.
!  It is designed for Variational Data Assimilation (4D-var) and sensitivity analyses. 
! Inverse capabilities are based on the adjoint code which is generated by 
! a source-to-source algorithmic differentiation (Tapenade software used).
!
!  DassFlow software includes few mostly independent "modules" with common architectures and structures:
!    - DassFlow 2DShallow (shallow water equations in (h,q), finite volumes), i.e. the present code.
!    - DassFlow3D  (non-linear Stokes equations, finite elements, mobile geometries, ALE).
!    - DassFlow 1D (shallow water equations in (S,Q), finite volumes or finite differences), river hydraulics.
!  Please consult the DassFlow webpage for more details: http://www.math.univ-toulouse.fr/DassFlow
!
! You have used DassFlow in an article, a scientific document etc ?  How to cite us ? Please consult the webpage.
! 
!  Many people have contributed to the DassFlow developments from the initial version to the latest ones.
!  Current main developers or scientific contributers are:
!               P. Brisset (CNES & Mathematics Institute of Toulouse & INSA Toulouse)
!               F. Couderc (CNRS & Mathematics Institute of Toulouse IMT)
!               P.-A. Garambois (INSA & ICUBE Strasbourg)
!               J. Monnier (INSA & Mathematics Institute of Toulouse IMT).
!               J.-P. Vila (INSA & Mathematics Institute of Toulouse IMT).
!  and former other developers (R. Madec, M. Honnorat and J. Marin).
!
!  Scientific contact : jerome.monnier@insa-toulouse.fr
!  Technical  contacts : frederic.couderc@math.univ-toulouse.fr, pierre.brisset@insa-toulouse.fr
!
!  This software is governed by the CeCILL license under French law and abiding by the rules of distribution
!  of free software. You can use, modify and/or redistribute the software under the terms of the CeCILL license
!  as circulated by CEA, CNRS and INRIA at the following URL: "http://www.cecill.info".
!
!  As a counterpart to the access to the source code and rights to copy, modify and redistribute granted by the
!  license, users are provided only with a limited warranty and the software's author, the holder of the economic
!  rights, and the successive licensors have only limited liability.
!
!  In this respect, the user's attention is drawn to the risks associated with loading, using, modifying and/or
!  developing or reproducing the software by the user in light of its specific status of free software, that may
!  mean that it is complicated to manipulate, and that also therefore means that it is reserved for developers and
!  experienced professionals having in-depth computer knowledge. Users are therefore encouraged to load and test the
!  software's suitability as regards their requirements in conditions enabling the security of their systems and/or
!  data to be ensured and, more generally, to use and operate it in the same conditions as regards security.
!
!  The fact that you are presently reading this means that you have had knowledge of the CeCILL license and that you
!  accept its terms.
!
!======================================================================================================================!
!> @file m_stdout.f90
!> @brief TODO


!> Module m_stdout.
module m_stdout
    use m_common
    implicit none
    
    ! Interfaces to routines and functions defined in base/geometry.f90
    interface print_stdout
!         subroutine print_stdout_1i(msg, i1)
!             import ip
!             implicit none
!             character(len=:), intent(in) :: msg
!             integer(ip), intent(in) :: i1
!         end subroutine
!         subroutine print_stdout_1r(msg, r1)
!             import rp
!             implicit none
!             character(len=:), intent(in) :: msg
!             real(rp), intent(in) :: r1
!         end subroutine
!         subroutine print_stdout_vi_vr(msg, r1, r2)
!             import ip
!             import rp
!             implicit none
!             character(len=:), intent(in) :: msg
!             integer(ip), dimension(:), intent(in) :: vi
!             real(rp), dimension(:), intent(in) :: vr
!         end subroutine
        procedure print_stdout_1i
        procedure print_stdout_1r
        procedure print_stdout_vi_vr
    end interface print_stdout


    contains
  

    subroutine print_stdout_1i(msg, i1)
        implicit none
        character(len=*), intent(in) :: msg
        integer(ip), intent(in) :: i1
        
        ! TODO
    
    end subroutine
  

    subroutine print_stdout_1r(msg, r1)
        implicit none
        character(len=*), intent(in) :: msg
        real(rp), intent(in) :: r1
        
        ! TODO
    
    end subroutine
  

    subroutine print_stdout_vi_vr(msg, vi, vr)
        implicit none
        character(len=*), intent(in) :: msg
        integer(ip), dimension(:), intent(in) :: vi
        real(rp), dimension(:), intent(in) :: vr
        
        if (msg == "dt") then
            write(6, '("nt = ",I8," t = ",ES12.5," / ",ES12.5," ( ",F5.1," % ) , dt = ",ES13.6)') vi(1), vr(1),&
                                                                                                  vr(2), &
                                                                                                  100._rp * vr(3), vr(4)
        end if
    
    end subroutine

end module m_stdout
